version: '3.8'

services:

  webserver:
    image: httpd:2.4
    container_name: webserver
    ports:
      - "${TEXT_PORT}:80"
    volumes:
      - /Users/phil/repos/python_text/notebooks_source:/srv/notebooks
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: bash -c
            "cp -a /srv/notebooks/_build/html/* /usr/local/apache2/htdocs/.
             && httpd-foreground
            "

  jupyterhub:
    build: hub_image
    image: phaustin/jupyterhub:textbook
    container_name: jupyterhub
    depends_on: [notebook]
    ports:
      - "${NB_PORT}:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - textbook_network

  notebook:
    build: notebook_image
    image: phaustin/notebook:textbook
    container_name: notebook

    # command: jupyterhub-singleuser

# set the network name
# this needs to be matched in jupyterhub_config.py by:
# c.DockerSpawner.network_name = 'textbook_network'
networks:
    textbook_network:
      driver: bridge
      name: textbook_network
