#
# docker compose variables set in .env
# also see environmental variables in run_docker.sh
#
version: '3.8'

services:

  webserver_text29:
    image: httpd:2.4
    container_name: ${WEB_CONTAINER_NAME}
    ports:
      - "${TEXT_PORT}:80"
    volumes:
      - ./notebooks_source:/srv/notebooks
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: bash -c
            "cp -a /srv/notebooks/_build/html/* /usr/local/apache2/htdocs/.
             && httpd-foreground
            "
