#conda-lock -f environment.yml -p linux-64
name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - python=3.7
  - base-notebook=2020.09.05
  - scipy
  # NOTE: pip required for running tests in this repo
  - pip=20
  - click
  - git
  - sphinx=3
  - jupyter
  - git
  - jupytext
  - sqlalchemy
  - pyyaml
  - docutils>=0.15
  - setuptools
  - sympy
  - matplotlib
  - bokeh
  - nbformat
  - nbconvert
  - nbclient
  - pillow
